name: 'Release published event'
on:
  release:
    types:
      - released

jobs:
  released:
    runs-on: ubuntu-latest
    steps:

      - name: Examples prod-build dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          repository: Apirone/examples-site
          event-type: deploy-wordpress
          client-payload: '{"tag": "${{ github.ref_name }}", "version": "${{ github.ref_name }}"}'

      - name: Send notification
        if: ${{ always() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          description: 'WordPress ${{ github.ref_name }} released now.'
